### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by rcthomas** [betterscientificsoftware/python-for-hpc#1]
This is great.  Could there perhaps be a "CONTRIBUTING.md" file with guidelines for how to contribute and verify that changes don't break the site?

**Comment by shuds13** [comment]
That is a very good point. The main BSSw site has [this](https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/HowToContribute.md).

My current thinking is contributors either fork the repo and make a pull request or just send me the content. Either way, I am responsible for content and breaking the site. I can, of course, point at the examples to use as a template. Alternatively,  I could use a form like the main BSSw site.

The other thought I had was to have a separate scratch/test repo, which anyone could push to, and contributions could be taken from there when they are ready.  I wondered if that might encourage people to push rough work initially, and then it could be cleaned up and formatted in place, before being put on the site.

Do you have any preferences, as a potential contributor?

**Comment by rcthomas** [comment]
You also mentioned sending content and you could incorporate that.  It's fairly easy for people to write markdown and submit it to you.  If you want to be the person worrying about breaking the site then that makes it easier in some ways!

**Comment by shuds13** [comment]
I have added a CONTRIBUTING.md file. Let me know if anything is unclear. I will add a link to it on the front end.

**Comment by rcthomas** [comment]
It looks good!
